---
title: "Colorado Preliminary State Legislative Districts"
description: |
    Colorado's Independent Redistricting Commission has released a 
  preliminary map for the 2022-2030 state legislative districts districts.
author:
  - name: Christopher T. Kenny
    url: https://www.christophertkenny.com/
  - name: Cory McCartan
    url: https://corymccartan.github.io/
date: 07-02-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```




# Data

We build a Census block-level dataset based on the 2010 Census shapes using `geomander` [@geomander]. We augment each of the 2010 blocks with 2020 estimated populations using `blockpop` [@blockpop]. Our analysis can then be conducted at the 2020 voting district level by aggregating 2010 block geographies to 2020 voting district geographies.

As with our [post on the CO preliminary Congressional Districts](https://corymccartan.github.io/redistricting21/posts/2021-06-25-colorado-preliminary-congressional-districts/), we build election data from the spatialized electoral data that the [Voting and Election Science Team](https://twitter.com/vest_team?lang=en) (VEST) creates. For the 2016 data, we average the presidential and senate races [@vest:16]. For the 2018 data, we average the Governor, Attorney General, and Secretary of State Elections [@vest:18]. And for the 2020 data, we average the presidential and senate races [@vest:20]. This provides a diverse set of races to use as baselines over time for evaluating the proposed plans. Each of these VEST datasets are estimated down to the block level and aggregated back up to the precinct level.
