name: Deploy site
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # Deploy to local repo
    - name: deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: site/docs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
